import Link from "next/link";
import Meta from "../components/layout/Meta";
export default function Home({ postList }) {
  return (
    <div className="container">
      <Meta
        title="home"
        descr="Generated by create next app"
        keywords="home,page"
      />

      <div className="home">
        <h1 className="text-center mt-2">this is home page</h1>
        <div className="mt-5">
          <div className="row">
            {postList.map((post) => {
              return (
                <div className="col-md-4 mt-5" key={post.id}>
                  <h4>{post.title.substring(0, 20)}</h4>
                  <p>{post.body.substring(0, 55)}</p>
                  <Link href="/post/[id]" as={`/post/${post.id}`}>
                    <a className="btn btn-outline-primary">read more</a>
                  </Link>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}

// export const getServerSideProps = async() => {

//     const res = await fetch('https://jsonplaceholder.typicode.com/posts/?_limit=12')
//     const postList = await res.json()

//     return {
//       props:{
//         postList
//       }
//     }
// }

export const getStaticProps = async () => {
  const res = await fetch(
    "https://jsonplaceholder.typicode.com/posts/?_limit=12"
  );
  const postList = await res.json();

  return {
    props: {
      postList,
    },
  };
};
